import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "../components";
import { cn } from "../shared";
import { QueryProvider } from "../components/QueryClientProvider/QueryProvider";

const nunito = Nunito({
	subsets: ["cyrillic"],
	variable: "--font-nunito",
	weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Next Burgers",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn("bg-slate-200 h-screen font-bold", nunito.className)}>
				<QueryProvider>
					<Header />
					<main>{children}</main>
				</QueryProvider>
			</body>
		</html>
	);
}
